"""empty message

Revision ID: 34960810da65
Revises: 6bddf032500c
Create Date: 2022-03-02 22:28:06.953157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34960810da65'
down_revision = '6bddf032500c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
